# -*- coding: utf-8 -*-
"""Exceções.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ZekkGMmB97SOkzS923qUi9hszY_sHurY

# **Exceções e Erros**

Enquanto desenvolvemos em Python nos deparamos com dois tipos de mensagens de erros: os de sintaxe e as exceções.

Os erros de sintaxe são aqueles comparados a erros de ortografia no português. Ou seja, erros de escrita ou de grafia correta. No caso da programação, são os erros que cometemos quando esquecemos de usar ":" ao final de um if ou while, por exemplo.

As exceções são diferentes, ocorrem durante a execução de um programa e podem e devem ser tratadas.

### **Exceções**

Por mais que um código esteja escrito corretamente, não possua erros de sintaxe, podem ocorrer erros diversos durante sua execução. Estes erros são nomeados exceções.

Quando estas exceções não são tratadas adequadamente, o código pode ter seu funcionamento comprometido e consequentemente interrompido.
"""

#Exemplo 1 de exceção
10*(1/0)

#Exemplo 2 de exceção
x = 4*variavel

#Exemplo 3 de exceção
b = "2"+3

"""### **Tratando exceções**

O tratamento de exceções é realizado através do bloco de código try e except.

Conforme pode ser visto no exemplo abaixo, o programa solicita um valor inteiro para a pessoa que o está utilizando. Caso este valor não seja inteiro, uma exceção é gerada e tratada.
"""

#Crie um programa que calcula e imprima o dobro de um valor inteiro informado pelo usuário
while True:
  try:
    valor = int(input("Informe um valor inteiro:"))
    print(f'O dobro de {valor} é {valor*2}')
    break
  except ValueError:
    print("O valor informado não era do tipo inteiro.")

"""A instrução try funciona da seguinte maneira:

*  Primeiramente, a cláusula try (o conjunto de instruções entre as palavras reservadas try e except ) é executada.

*  Se nenhuma exceção ocorrer, a cláusula except é ignorada e a execução da instrução try é finalizada.

*  Se ocorrer uma exceção durante a execução de uma cláusura try, as instruções remanescentes na cláusula são ignoradas. Se o tipo da exceção ocorrida tiver sido previsto em algum except, essa cláusura except é executada, e então depois a execução continua após o bloco try/except.

*  Se a exceção levantada não corresponder a nenhuma exceção listada na cláusula de exceção, então ela é entregue a uma instrução try mais externa. Se não existir nenhum tratador previsto para tal exceção, trata-se de uma exceção não tratada e a execução do programa termina com uma mensagem de erro.

### **Materiais complementares**

Maiores informações sobre exceções podem ser encontrados em: https://docs.python.org/pt-br/3/tutorial/errors.html
"""